theme = "my_theme"

[editor]
mouse = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["file-name", "file-modification-indicator"]
center = ["spinner"]
right = ["diagnostics", "position", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
X = "extend_line_above"

[keys.normal.space]
q = ":quit"
Q = ":quit!"
s = ":write"
S = ":write!"
x = ":x"
